# Generated by Django 4.1.2 on 2023-03-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(default='', upload_to='Shop/images')),
                ('product_name', models.CharField(max_length=100)),
                ('product_price', models.IntegerField(default=0)),
                ('product_Desc', models.CharField(max_length=500)),
                ('product_publish', models.DateField()),
            ],
        ),
    ]
