# Generated by Django 4.1.2 on 2023-03-21 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='catogery',
            field=models.CharField(default='Shop', max_length=1000),
        ),
    ]
