# Generated by Django 4.1.2 on 2023-03-22 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_catogery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('Msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('desc', models.CharField(default='', max_length=1000)),
                ('publish', models.DateField()),
                ('catogery', models.CharField(default='Shop', max_length=1000)),
            ],
        ),
    ]
