# Generated by Django 4.1.2 on 2023-03-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='catogery',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='publish',
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(default='', max_length=100),
        ),
    ]
