# Generated by Django 4.1.2 on 2023-03-23 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_contact_catogery_remove_contact_publish_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderedBooked',
            fields=[
                ('Msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(default='', max_length=100)),
                ('phone', models.CharField(default='', max_length=100)),
                ('address', models.CharField(default='', max_length=1000)),
            ],
        ),
    ]
