# Generated by Django 4.1.2 on 2023-03-24 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_orderedbooked'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderedbooked',
            old_name='Msg_id',
            new_name='Order_id',
        ),
    ]
