# Generated by Django 4.1.2 on 2023-03-24 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_rename_msg_id_orderedbooked_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedbooked',
            name='City',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='orderedbooked',
            name='State',
            field=models.CharField(default='', max_length=200),
        ),
    ]
