# Generated by Django 4.1.2 on 2023-03-29 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_orderedbooked_city_orderedbooked_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderedbooked',
            name='amount',
            field=models.IntegerField(default='', max_length=100),
        ),
    ]
