# Generated by Django 4.1.2 on 2023-03-29 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_orderedbooked_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedbooked',
            name='amount',
            field=models.IntegerField(default=0, max_length=100),
        ),
    ]
