# Generated by Django 4.1.2 on 2023-03-29 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_alter_orderedbooked_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedbooked',
            name='amount',
            field=models.BigIntegerField(default=0, null=True),
        ),
    ]
