# Generated by Django 4.1.2 on 2023-03-29 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_alter_orderedbooked_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderedbooked',
            name='amount',
        ),
    ]
